### ISSUE TITLE
Develop a Home Page

### ISSUE THREAD

**Issue by madwirblet** [rileycleavenger/StockBuddy#12]
Combination of Piper and Maddy's designs:

Include (not limited to)
- Narrow filter results sidebar in the main search box 
- Pop-up for investing for dummies 
- Suggestions from the live market

**Comment by piper-jones** [comment]
Maddy
Nav bar stylization
Main boxes
notepad (bottom right box)

Piper
Filters
two buttons under the main
window popping up when you hit For Dummies button
(attempt the rotating box with different colored panels (top right box)?)

**Comment by madwirblet** [comment]
Completion set back a few days.

**Comment by madwirblet** [comment]
Completion pushed back
