### ISSUE TITLE
Make a SQL Database Schema

### ISSUE THREAD

**Issue by rileycleavenger** [rileycleavenger/StockBuddy#22]
develop a data for how we are going to store our data, remembering we are going to store the following:
- user data
- suggestion history (including user, stocks suggested, how many shares, if the suggestion was to buy or sell, date of suggestion)

*anything else you can think of that we need to store should be in this as well, this is just what I can think of off the top of my head

**Comment by Dravani** [comment]
<img width="873" alt="Screenshot 2024-06-27 at 3 20 50 PM" src="https://github.com/rileycleavenger/StockBuddy/assets/42421220/ce6382f2-ad32-41fb-a29c-2f7629ea9c44">

**Comment by Dravani** [comment]
<img width="638" alt="Screenshot 2024-07-11 at 1 28 40 PM" src="https://github.com/rileycleavenger/StockBuddy/assets/42421220/845c6f2c-ff1d-4621-b9c6-2cbb0c0f00ae">

**Comment by rileycleavenger** [comment]
LGTMQ
