### ISSUE TITLE
Create Database and Tables

### ISSUE THREAD

**Issue by rileycleavenger** [rileycleavenger/StockBuddy#27]
Use Google Cloud SQL and the free $300 for being a student to setup the Database Tables represented by @Dravani 's schema.

**Comment by Dravani** [comment]
![Uploading Screenshot 2024-07-11 at 1.28.40 PM.png…]()

**Comment by madwirblet** [comment]
![Screenshot 2024-07-14 at 7 13 48 AM](https://github.com/user-attachments/assets/33149386-0c1d-4544-9c37-753db48cd0a4)
![Screenshot 2024-07-14 at 7 13 57 AM](https://github.com/user-attachments/assets/77f28a67-cde3-4762-8583-a7c9072c6324)
![Screenshot 2024-07-14 at 7 14 08 AM](https://github.com/user-attachments/assets/a71fbdd1-6959-43d7-998c-acbe477234f2)
I am not sure how to upload the database but here is screenshots from Cloud Shell in Google Cloud
