### ISSUE TITLE
Solve testdata issue for Alpha Vantage API

### ISSUE THREAD

**Issue by dos-2** [rileycleavenger/StockBuddy#34]
* Probably easiest to just make a request and use that data as our testdata, and then create an option in the code for us to use the testdata instead of making an actual request

**Comment by rileycleavenger** [comment]
- [x] Create table in database for stock historical data with columns: ticker, open price, low price, high price, volume, date, date_pulled 
- [x] Update alpha vantage python scripts to output historical data to database table (above) when ran (historical_data func will store data)

**Comment by rileycleavenger** [comment]
@Nikola611 solved this with #41
